# Generated by Django 5.1.1 on 2024-09-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_rename_username_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imap_service',
            field=models.CharField(default='imap.gmail.com', max_length=20),
        ),
    ]
