# Generated by Django 5.1.1 on 2024-09-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0003_user_imap_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='imap_service',
            new_name='imap_server',
        ),
    ]
